function armToolRecipe(resultArmTool, armTool, gemstone, ingot){

Recipes.addShaped({ id: resultArmTool, count: 1, data: 0 }, [
    " g ",
    "s#s",
    " g "
], ["#", armTool, 0, "g", gemstone, 0, "s", ingot, 0]);
}

armToolRecipe(ItemID.inferium_sword, VanillaItemID.diamond_sword, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_pickaxe, VanillaItemID.diamond_pickaxe, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_axe, VanillaItemID.diamond_axe, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_shovel, VanillaItemID.diamond_shovel, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_hoe, VanillaItemID.diamond_hoe, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.prudentium_sword, ItemID.inferium_sword, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_pickaxe, ItemID.inferium_pickaxe, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_axe, ItemID.inferium_axe, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_shovel, ItemID.inferium_shovel, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_hoe, ItemID.inferium_hoe, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.intermedium_sword, ItemID.prudentium_sword, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_pickaxe, ItemID.prudentium_pickaxe, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_axe, ItemID.prudentium_axe, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_shovel, ItemID.prudentium_shovel, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_hoe, ItemID.prudentium_hoe, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.superium_sword, ItemID.intermedium_sword, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_pickaxe, ItemID.intermedium_pickaxe, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_axe, ItemID.intermedium_axe, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_shovel, ItemID.intermedium_shovel, ItemID.superium_gemstone, ItemID.superium_ingot )
armToolRecipe(ItemID.superium_hoe, ItemID.intermedium_hoe, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.supremium_sword, ItemID.superium_sword, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_pickaxe, ItemID.superium_pickaxe, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_axe, ItemID.superium_axe, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_shovel, ItemID.superium_shovel, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_hoe, ItemID.superium_hoe, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.inferium_helmet, VanillaItemID.diamond_helmet, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_chestplate, VanillaItemID.diamond_chestplate, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_leggings, VanillaItemID.diamond_leggings, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.inferium_boots, VanillaItemID.diamond_boots, ItemID.inferium_gemstone, ItemID.inferium_ingot)
armToolRecipe(ItemID.prudentium_helmet, ItemID.inferium_helmet, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_chestplate, ItemID.inferium_chestplate, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_leggings, ItemID.inferium_leggings, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.prudentium_boots, ItemID.inferium_boots, ItemID.prudentium_gemstone, ItemID.prudentium_ingot)
armToolRecipe(ItemID.intermedium_helmet, ItemID.prudentium_helmet, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_chestplate, ItemID.prudentium_chestplate, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_leggings, ItemID.prudentium_leggings, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.intermedium_boots, ItemID.prudentium_boots, ItemID.intermedium_gemstone, ItemID.intermedium_ingot)
armToolRecipe(ItemID.superium_helmet, ItemID.intermedium_helmet, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_chestplate, ItemID.intermedium_chestplate, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_leggings, ItemID.intermedium_leggings, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.superium_boots, ItemID.intermedium_boots, ItemID.superium_gemstone, ItemID.superium_ingot)
armToolRecipe(ItemID.supremium_helmet, ItemID.superium_helmet, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_chestplate, ItemID.superium_chestplate, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_leggings, ItemID.superium_leggings, ItemID.supremium_gemstone, ItemID.supremium_ingot)
armToolRecipe(ItemID.supremium_boots, ItemID.superium_boots, ItemID.supremium_gemstone, ItemID.supremium_ingot)

